"""change manufacturer id nullable = True in Equipment

Revision ID: 20bad72e0c85
Revises: 89cc8040376d
Create Date: 2026-05-13 14:44:03.248102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20bad72e0c85'
down_revision: Union[str, Sequence[str], None] = '89cc8040376d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipment', 'manufacturer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipment', 'manufacturer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
