"""add manufacturer_id nullable

Revision ID: 89cc8040376d
Revises: 5c77bddfef71
Create Date: 2026-05-13 14:39:36.428182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89cc8040376d'
down_revision: Union[str, Sequence[str], None] = '5c77bddfef71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturer_id'), 'manufacturer', ['id'], unique=False)
    op.add_column('equipment', sa.Column('manufacturer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'equipment', 'manufacturer', ['manufacturer_id'], ['id'])
    op.drop_column('equipment', 'manufacturer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('manufacturer', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_column('equipment', 'manufacturer_id')
    op.drop_index(op.f('ix_manufacturer_id'), table_name='manufacturer')
    op.drop_table('manufacturer')
    # ### end Alembic commands ###
