"""add status tables for Defect and Equipment

Revision ID: a4a5e5d54f12
Revises: 20bad72e0c85
Create Date: 2026-05-13 15:00:35.142364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a5e5d54f12'
down_revision: Union[str, Sequence[str], None] = '20bad72e0c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defect_status_id'), 'defect_status', ['id'], unique=False)
    op.create_table('equipment_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_status_id'), 'equipment_status', ['id'], unique=False)
    op.add_column('defect', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'defect', 'defect_status', ['status_id'], ['id'])
    op.drop_column('defect', 'status')
    op.add_column('equipment', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'equipment', 'equipment_status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_column('equipment', 'status_id')
    op.add_column('defect', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'defect', type_='foreignkey')
    op.drop_column('defect', 'status_id')
    op.drop_index(op.f('ix_equipment_status_id'), table_name='equipment_status')
    op.drop_table('equipment_status')
    op.drop_index(op.f('ix_defect_status_id'), table_name='defect_status')
    op.drop_table('defect_status')
    # ### end Alembic commands ###
