"""remove string status and set nullable=False

Revision ID: f8b492a6528e
Revises: a4a5e5d54f12
Create Date: 2026-05-13 15:06:21.547844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b492a6528e'
down_revision: Union[str, Sequence[str], None] = 'a4a5e5d54f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('defect', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipment', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('equipment', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('equipment', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('defect', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
